# -*- coding: utf-8 -*-
"""dados

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mY8aVwcuW2neHqGqHuFfkuSkqTi7TBot
"""

import random
import matplotlib.pyplot as plot 
def dados(num, total):
  for i in range(num):
    dado1 = random.randint(1,6)
    dado2 = random.randint(1,6)
    res = dado1 + dado2
    total.append(res)
    print('dados', dado1, '-', dado2)
  print('suma de los dados', total)

  intervalos = range(2,13)
  plot.hist(x=total, bins=intervalos, color='#00FFEC', rwidth=0.85)
  plot.title('Grafica de los resultados')
  plot.xlabel('Suma')
  plot.ylabel('Repeticiones')
  plot.grid(color='r', linestyle='dotted', linewidth=1)
  plot.xticks(intervalos)

array = []
dados(10, array);
# dados(100, array);
# dados(1000, array);
# dados(10000, array);
# dados(100000, array);